"""Initial migration

Revision ID: abaf779661aa
Revises: 
Create Date: 2026-01-05 11:09:36.994965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = 'abaf779661aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('postcode_hash', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('system_type', sa.String(length=10), nullable=False),
    sa.Column('system_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('climate_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('climate_source', sa.String(length=50), nullable=True),
    sa.Column('annual_energy_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_energy_kwh', sa.ARRAY(sa.Numeric(precision=10, scale=2)), nullable=True),
    sa.Column('confidence_band_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regional_factors_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculation_version', sa.String(length=20), nullable=True),
    sa.CheckConstraint("system_type IN ('solar', 'wind')", name='check_system_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('system_type', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_documents_category', 'rag_documents', ['category'], unique=False)
    op.create_index('idx_rag_documents_embedding_cosine', 'rag_documents', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_rag_documents_system_type', 'rag_documents', ['system_type'], unique=False)
    op.create_table('regional_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('system_type', sa.String(length=10), nullable=False),
    sa.Column('correction_factor', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('confidence_band_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('mean_deviation', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('std_deviation', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("system_type IN ('solar', 'wind')", name='check_system_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region', 'system_type', name='uq_region_system_type')
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('calculation_id', sa.UUID(), nullable=True),
    sa.Column('actual_annual_kwh', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('performance_period_months', sa.Integer(), nullable=True),
    sa.Column('predicted_annual_kwh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deviation_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('regional_factors')
    op.drop_index('idx_rag_documents_system_type', table_name='rag_documents')
    op.drop_index('idx_rag_documents_embedding_cosine', table_name='rag_documents', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_rag_documents_category', table_name='rag_documents')
    op.drop_table('rag_documents')
    op.drop_table('calculations')
    # ### end Alembic commands ###
